//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDetail.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public int id { get; set; }
        public string varName { get; set; }
        public Nullable<System.DateTime> dtCreationDate { get; set; }
        public Nullable<int> intCreatedBy { get; set; }
        public Nullable<int> intPrice { get; set; }
    }
}
