//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDetail.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        public int id { get; set; }
        public Nullable<int> intItemId { get; set; }
        public Nullable<decimal> flQuantity { get; set; }
        public Nullable<decimal> flRate { get; set; }
        public Nullable<decimal> flTotal { get; set; }
        public Nullable<int> intMasterId { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
    }
}
